Add git to the ko image
Sometimes, when building projects that depend on private modules, go will
attempt to invoke git to download those modules.  This causes
Predictably Bad Things to happen:

    2023/10/19 21:45:46 Using base cgr.dev/chainguard/static:latest@sha256:ef5add7fd46cf1ce7d33d6de517833ac5c7e749db9b15249f9c472a772f3af27 for ..redacted...
    2023/10/19 21:45:47 Building ..redacted... for linux/s390x
    2023/10/19 21:45:47 Building ..redacted... for linux/386
    2023/10/19 21:45:47 Building ..redacted... for linux/arm/v7
    2023/10/19 21:45:47 Building ..redacted... for linux/amd64
    2023/10/19 21:46:17 Building ..redacted... for linux/arm64
    2023/10/19 21:46:17 Building ..redacted... for linux/arm/v6
    Error: failed to publish images: error building "ko://..redacted...": build: go build: exit status 1: go: downloading ...redacted... v1.2.3
    main.go:6:2: git init --bare in ...redacted.../go/pkg/mod/cache/vcs/698e3376d5ab1d9b02034561bf5649e96bda9b3ebabfda932ed4929dfa91b03c: exec: "git": executable file not found in $PATH

This change adds git to the list of packages to be included in the
image build.

Signed-off-by: Chris Weyl <cweyl@ibm.com>